### PR TITLE
Filter out files _before_ parsing

### LINKED ISSUE #265: Files ignored may still cause parse errors
This came up when testing Regal against a repo where a few files were used as templates, i.e. something like:
```
package {{org_name}}.authz

# ...
```
Now this is obviously not a valid Rego file, and should be ignored for evaluation. But since we do the ignore check *after* we've parsed the files, this fails even when ignoring the directory or these files.

Doing the ignore check in Rego is likely the best option for rule level ignores, as you won't want to ignore a parse error only for a certain rule, but perhaps we'd need to make the global ignore check in Go before the files are parsed.

Alternatively, we could still leverage the check in Rego, but have Regal do something like:

- Gather all files lined up for evaluation.
- Pass the list for evaluation using the config policy, which...
- Returns the list with any files and directories that should be ignored removed.

This options would be more arduous, but it would benefit from having the same ignore logic for both global ignore directives as well as for rule level ignores.

### PR DESCRIPTION
**Pull request by anderseknert**
Also:
* Allow files to be provided either from file paths, *or* programmatically as modules.
* Marshal config directly to Config struct, and prefer to use the struct rather than passing around the config as a map.

Fixes #265

### CODE REVIEW

File: internal/io/io.go [hunk 1]
```diff
@@ -72,6 +72,23 @@ func JSONRoundTrip(from any, to any) error {
 	return json.Unmarshal(bs, to) //nolint:wrapcheck
 }
 
+// YAMLRoundTrip convert any value to YAML and back again.
+func YAMLRoundTrip(from any, to any) error {
```
Comment (kristiansvalland) [inline internal/io/io.go:76]: While I am not very familiar with (un)marshalling YAML, I do not immediately see how making a roundtrip via YAML as the intermediate is any different from JSON when considering the end result. Or is there some go types that would behave differently in this case?

File: pkg/config/config.go [hunk 2]
```diff
@@ -135,3 +145,45 @@ func (rule *Rule) UnmarshalJSON(data []byte) error {
...
+
+		rule.Ignore = dst
+	}
+
+	delete(result, "enabled")
+
+	rule.Level = level
+	rule.Extra = result
+
+	return nil
```
Comment (kristiansvalland) [inline pkg/config/config.go:188]: Probably not a big improvement, but could/should this part be shared with `UnmarshalJSON` to reduce code duplication?

**Review by kristiansvalland — APPROVED** [review]
This is a great refactor and fix of the ignore logic. 🙂

I had just one question and one minor suggestion, but those are in no way blocking for this PR and can be ignored if they are wrong or you disagree.

File: internal/io/io.go (hunk 1 above)
Comment (anderseknert) [reply internal/io/io.go:76]: No, you're right. This remained from a point where I considered ditching JSON altogether, but I realized later we need that for output formats. I'll have this removed before merge.

File: pkg/config/config.go (hunk 2 above)
Comment (anderseknert) [reply pkg/config/config.go]: Fair enough! Done.
