### PR TITLE
Don't call completion providers inside of comments

### LINKED ISSUE #826: Code completion in comments (Zed)
For some reason, Zed seems to give code completion inside of comments. We should investigate why that differs from VS Code, where I don't seem to be able to reproduce this.

Screenshot 2024-06-12 at 14 14 56

### PR DESCRIPTION
**Pull request by anderseknert**
It seems like this is handled client side by some editors, but Zed triggered completion requests inside of comments. While we could have each provider handle this, I think an early exit in the manager already is a better solution, as there's unlikely to be any provider that wants to do suggestions in a comment. If that changes in the future, we'll handle it then.

Fixes #826

### CODE REVIEW

File: internal/lsp/completions/manager.go [hunk 1]
```diff
@@ -70,3 +77,19 @@ func (m *Manager) Run(params types.CompletionParams, opts *providers.Options) ([
...
 }
+
+func (m *Manager) isInsideOfComment(params types.CompletionParams) bool {
+	if module, ok := m.c.GetModule(params.TextDocument.URI); ok {
+		for _, comment := range module.Comments {
+			cp := rego.PositionFromLocation(comment.Location)
+
+			if cp.Line == params.Position.Line {
+				if cp.Character <= params.Position.Character {
+					return true
```
Comment (charlieegan3) [inline internal/lsp/completions/manager.go:88]: This is nice!

**Review by charlieegan3 — APPROVED** [review]
